runtime: python311

service: rocaleda-fp-orchestrator-ms

entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app

instance_class: F2

readiness_check:
    path: "/health"  
    check_interval_sec: 60  
    timeout_sec: 60  
    failure_threshold: 5 

env_variables:
    CUSTOMERS_MS: VAR_CUSTOMERS_MS
    CANDIDATES_MS: VAR_CANDIDATES_MS

vpc_access_connector:
    name: projects/VAR_PROJECT_ID/locations/VAR_REGION/connectors/VAR_VPC_CONNECTOR
    egress_setting: all-traffic
