steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
      - -c
      - |
        sed -i "s|VAR_CANDIDATES_MS|$_CANDIDATES_MS|g" app.yaml
        sed -i "s|VAR_CUSTOMERS_MS|$_CUSTOMERS_MS|g" app.yaml
        sed -i "s|VAR_PROJECT_ID|$PROJECT_ID|g" app.yaml
        sed -i "s|VAR_REGION|$LOCATION|g" app.yaml
        sed -i "s|VAR_VPC_CONNECTOR|$_VPC_CONNECTOR_NAME|g" app.yaml
        gcloud app deploy
timeout: "1600s"
